export enum ExpenseCategory {
  INVENTORY_PURCHASE = 'inventory_purchase',
  RENT = 'rent',
  UTILITIES = 'utilities',
  INTERNET_PHONE = 'internet_phone',
  SALARIES = 'salaries',
  TAXES = 'taxes',
  MAINTENANCE = 'maintenance',
  MARKETING = 'marketing',
  FUEL = 'fuel',
  CLEANING = 'cleaning',
  OFFICE_SUPPLIES = 'office_supplies',
  DELIVERY = 'delivery',
  EQUIPMENT = 'equipment',
  SOFTWARE = 'software',
  INSURANCE = 'insurance',
  BANK_FEES = 'bank_fees',
  OTHER = 'other',
}
